package ext;

import ext.AbstractComponent;
import ext.Container;
import ext.dom.Element;
import ext.Element;

@:native ("Ext.Component")
extern class Component extends AbstractComponent {

	//public var dockPositions:Dynamic;
	public static var dockPositions:Dynamic;

	public function addCls (cls:String, prefix:String, suffix:String):Void;
	public function destroy ():Void;
	public function disable ():Void;
	public function enable ():Void;
	public function getBaseCls ():String;
	public function getBorder ():Dynamic;
	public function getBottom ():Dynamic;
	public function getCentered ():Bool;
	public function getCls ():String;
	public function getContentEl ():Dynamic;
	public function getData ():Dynamic;
	public function getDisabled ():Bool;
	public function getDisabledCls ():String;
	public function getDocked ():String;
	public function getDraggable ():Dynamic;
	public function getDroppable ():Dynamic;
	public function getEl ():Element;
	public function getHeight ():Float;
	public function getHidden ():Bool;
	public function getHideOnMaskTap ():Bool;
	public function getHtml ():Dynamic;
	public function getItemId ():String;
	public function getLeft ():Dynamic;
	public function getMargin ():Dynamic;
	public function getModal ():Bool;
	public function getPadding ():Dynamic;
	public function getPlugins ():Dynamic;
	public function getRenderTo ():Element;
	public function getRenderTpl ():Dynamic;
	public function getRight ():Dynamic;
	public function getSize ():Dynamic;
	public function getStyle ():Dynamic;
	public function getStyleHtmlCls ():String;
	public function getStyleHtmlContent ():Bool;
	public function getTop ():Dynamic;
	public function getTpl ():Dynamic;
	public function getTplWriteMode ():String;
	public function getTranslatable ():Dynamic;
	public function getWidth ():Float;
	public function getXTypes ():String;
	public function getZIndex ():Float;
	public function hide ():Void;
	public function isDisabled ():Bool;
	public function isHidden ():Bool;
	public function isXType (xtype:String, ?shallow:Bool):Bool;
	public function new (config:Dynamic):Void;
	public function removeCls (cls:String, prefix:String, suffix:String):Void;
	public function setBaseCls (baseCls:String):Void;
	public function setBorder (border:Dynamic):Void;
	public function setBottom (bottom:Dynamic):Void;
	public function setCentered (centered:Bool):Void;
	public function setCls (cls:String):Void;
	public function setContentEl (contentEl:Dynamic):Void;
	public function setData (data:Dynamic):Void;
	public function setDisabled (disabled:Bool):Void;
	public function setDisabledCls (disabledCls:String):Void;
	public function setDocked (docked:String):Void;
	public function setDraggable (draggable:Dynamic):Void;
	public function setDroppable (droppable:Dynamic):Void;
	public function setHeight (height:Float):Void;
	public function setHidden (hidden:Bool):Void;
	public function setHideOnMaskTap (hideOnMaskTap:Bool):Void;
	public function setHtml (html:Dynamic):Void;
	public function setItemId (itemId:String):Void;
	public function setLeft (left:Dynamic):Void;
	public function setMargin (margin:Dynamic):Void;
	public function setModal (modal:Bool):Void;
	public function setPadding (padding:Dynamic):Void;
	public function setPlugins (plugins:Dynamic):Void;
	public function setRenderTo (renderTo:Element):Void;
	public function setRenderTpl (renderTpl:Dynamic):Void;
	public function setRight (right:Dynamic):Void;
	public function setSize (width:Float, height:Float):Void;
	public function setStyle (style:Dynamic):Void;
	public function setStyleHtmlCls (styleHtmlCls:String):Void;
	public function setStyleHtmlContent (styleHtmlContent:Bool):Void;
	public function setTop (top:Dynamic):Void;
	public function setTpl (tpl:Dynamic):Void;
	public function setTplWriteMode (tplWriteMode:String):Void;
	public function setTranslatable (translatable:Dynamic):Void;
	public function setWidth (width:Float):Void;
	public function setZIndex (zIndex:Float):Void;
	public function show ():Void;
	public function showBy (alignTo:Dynamic):Void;
	public function up (selector:String):Container;
	public function updateStyleHtmlCls (newHtmlCls:Dynamic, oldHtmlCls:Dynamic):Void;

}